kind: Namespace
apiVersion: v1
metadata:
  name: sage
  labels:
    name: sage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-deployment
  namespace: sage
  labels:
    app: sage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sage
  template:
    metadata:
      labels:
        app: sage
    spec:
      nodeSelector:
        purpose: general
      containers:
        - name: sage
          image: josegarita/page:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sage-service
  namespace: sage
spec:
  selector:
    app: sage
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sage
  namespace: sage
spec:
  hosts:
    - '*'
  gateways:
    - istio-custom/devops-gateway
  http:
    - name: 'sage-routes'
      match:
        - uri:
            prefix: '/sage'
      route:
        - destination:
            host: sage-service.sage.svc.cluster.local